server {
    listen       8080;
    server_name  localhost;

    gzip         on;
    gzip_static  on;
    gzip_types   text/plain application/json text/css application/javascript application/xml;
    gzip_min_length 1025;

    location = /healthz {
        return 204;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
